### ISSUE TITLE
Can you modify assemblies?

### ISSUE THREAD

**Issue by gurrenm3** [kagurazakasanae/Il2CppAssemblyUnhollower-YuanShen#1]
I've seen people use Il2CppAssemblyUnhollower to view and modify assembly from games. Have you managed to modify the assemblies yet?

Thanks

**Comment by kagurazakasanae** [comment]
you will need to inject your own dll into game and do hook on il2cpp functions in order to archive this, with Il2CppAssemblyUnhollower you can only view the structure of game assembly.

**Comment by gurrenm3** [comment]
I see. With a method like this, what's the likelihood of getting banned? I'd like to try modifying how many primogems I get from quest rewards

**Comment by kagurazakasanae** [comment]
this part is done by server and modify it on client-side will not help.
